on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish to hex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27.0'
          elixir-version: '1.17.2'
      - uses: cucumber/action-publish-hex@v1.0.0
        with:
          hex-api-token: ${{ secrets.HEX_API_KEY }}
